name: Build/Upload tslib package

on:
  release:
    types:
      - published

  push:
    branches:
      - "release/**"
      - "test/build/**"
      - "temp/gh-workflow-build"

  workflow_dispatch:

env:
  DEFAULT_PYTHON_VERSION: "3.10"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install poetry
        run: |
          pipx install poetry
      - name: Set up Python ${{ env.DEFAULT_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Set Poetry environment
        run: |
          poetry env use ${{ env.DEFAULT_PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Build package
        run: |
          poetry build
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: distfiles
          path: dist/
          if-no-files-found: error

  upload-testpypi:
    name: Upload to TestPyPI
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/test/build')

    steps:
      - name: Download distfiles
        uses: actions/download-artifact@v4
        with:
          name: distfiles
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
